name: Wöchentliches Notebook ausführen und CSV in Google Drive speichern

on:
  schedule:
    - cron: '0 0 * * 1'  # Jeden Montag um Mitternacht UTC ausführen
  workflow_dispatch:  # Ermöglicht manuelles Ausführen des Workflows

jobs:
  run-notebook:
    runs-on: ubuntu-latest  # Ubuntu-Runner verwenden

    steps:
      - name: Repository klonen
        uses: actions/checkout@v3

      - name: Python 3 und Abhängigkeiten installieren
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-pip python3-dev
          pip install --upgrade pip
          pip install virtualenv
          python3 -m venv venv  # Erstelle eine virtuelle Umgebung
          source venv/bin/activate  # Aktiviere die virtuelle Umgebung
          pip install pandas google-auth google-auth-httplib2 google-auth-oauthlib google-api-python-client jupyter

      - name: Notebook ausführen
        run: |
          source venv/bin/activate  # Stelle sicher, dass die virtuelle Umgebung aktiviert ist
          jupyter nbconvert --execute --to notebook --inplace notebooks/reddit-skript.ipynb
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}  # Zugriff auf das Google Service-Konto
